### ISSUE TITLE
ssh-agent authentication not supported

### ISSUE THREAD

**Issue by loztcf** [spantaleev/sftpman#13]
If auth_method is set to publickey sftpman forces the user to specify a path to any ssh_key.
As ssh-agent is used it's not possible to tell this path.
sshfs/ssh are working out of the box with ssh-agent if no "-i identity_file" is given.

**Comment by spantaleev** [comment]
I've added support for a new "Authentication agent" ("SSH agent") authentication method. It's part of `sftpman=1.2.1` and `sftman-gtk=1.1`
