### ISSUE TITLE
Usernames with underscore are not allowed

### ISSUE THREAD

**Issue by mwm-webdesign** [spantaleev/sftpman#9]
It's not uncommon for usernames to contain an underscore character, but sftpman refuses them and throws the error : « Usernames can only contain letters, at signs and digits. »

Edit : I user sftpman-gtk, so I'm not sure if this applies to gtk only.

**Comment by spantaleev** [comment]
@mwm-webdesign, this should apply to both sftpman and sftpman-gtk.

I believe the validation logic is only in sftpman's code though.
I've just fixed it in 736f64600263f6, which I also released as sftpman 1.1.2.
Updating to that should make it work.

Thanks for reporting the problem! :+1:
